# Generated by Django 4.0.6 on 2022-08-30 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=90, verbose_name='Playlist name')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Owner name')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='Last update')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('img_cover_url', models.CharField(max_length=255, null=True, verbose_name="Playlist's cover url")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=90, verbose_name='Artist')),
                ('track_name', models.CharField(max_length=255, verbose_name='Track name')),
                ('duration', models.TimeField(verbose_name='Duration')),
                ('img_cover_url', models.CharField(max_length=255, null=True, verbose_name="Track's cover url")),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist', verbose_name='Playlist')),
            ],
        ),
    ]
