# Generated by Django 4.0.6 on 2022-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_playlist_options_alter_playlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(max_length=20, verbose_name='Duration'),
        ),
    ]
